[package]
name = "fliters"
version = "0.1.0"
edition = "2021"

[dependencies]
cstr = "0.2.11"
hound = "3.5"
rodio = { version = "0.17.1", default_features = false, features = ["wav"] }

[build-dependencies]
cc = "1.0.83"
